name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}
on:
  #push:
  workflow_dispatch:
    inputs:
      debug: { description: 'Enable Debug mode', type: boolean, required: false, default: false}
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.event_name}}"
          echo "Branch: ${{ github.ref_name }}" 
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: "[debug] Print when triggered from main"
        if: ${{ inputs.debug && github.ref_name == 'main' }}
        run: echo "This job was triggered from the main branch"

      - name: Greeting
        run: echo "Hello, ${{ github.actor }}! Welcome to the GitHub Actions course."

