name: 08 - Using Variables
on:
  #push:
  workflow_dispatch:
env:
  WORKFLOW_VAR: 'I am a workflow env var'
  OVERWRITTEN: 'I will be overwritten'
  UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'I am a default value' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env var'
      OVERWRITTEN: 'I am a job var and I overwrite the workflow var'
    steps:
      - name: Show VariablesPrint Env Variables
        env:
          STEP_VAR: 'I am a step env var'
          step_var2: 'I am another step var'
        run: |
          echo "Step env var: $STEP_VAR"
          echo "Step env var 2: $step_var2"
          echo "Job env var: $JOB_VAR"
          echo "Workflow env var: $WORKFLOW_VAR"
          echo "Overwritten var: $OVERWRITTEN"

      - name: Overwrite Job Variable
        env:
          OVERWRITTEN: 'I have been overwritten at the step level'
        run: |
          echo "Step env var: $OVERWRITTEN"

  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: |
          echo "Repo Variable: ${{ vars.REPOSITORY_VAR }}"
  
  echo-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print Prod Variables
        run: |
          echo "Environment Variable: ${{ vars.ENV_VAR_PROD }}"
          echo "Undefined Variable with Default: $UNDEFINED_VAR_WITH_DEFAULT"
