name: 14 - Working with Artifacts
on:
  workflow_dispatch:

env:
  build-artifact-key: 'app-${{ github.sha }}'
  test-coverage-key: 'test-coverage-${{ github.sha }}'

jobs:
  test-build:
    runs-on: uvuntu-latest
    defaults:
      run:
        working-directory: ./13-caching/react-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        
      - name: Download cached dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ./13-caching/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install

      - name: Unit tests
        run: npm run test
        
      - name: Generate coverage report
        run: npm run test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.test-coverage-key }}
          path: ./13-caching/react-app/coverage

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: ./13-caching/react-app/build

  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: build

      - name: List files
        run: ls -R