name: 17 - 3 - Custom Actions - Docker
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to ping'
        required: true
        type: string
        default: 'https://www.google.com'
jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ping URL using custom Docker action
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max-trials: 5
          delay-seconds: 3