name: 18 - 1 - Reusable Workflows - Reusable Definition
on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true
    outputs:
      build-status:
        description: The status of the build process
        value: ${{ jobs.deploy.outputs.build-status }}
      url:
        description: The url of the deployed version
        value: ${{ jobs.deploy.outputs.url }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.buildt.outputs.build-status }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
          echo "Building using directory ${{ inputs.target-directory }}"
          # Simulate build process
          sleep 2
          echo "Build completed successfully."
          echo "build_status=success" >> $GITHUB_OUTPUT

      - name: Deploy
        id: deploy
        run: |
          echo "Deploying application from directory ${{ inputs.target-directory }}"
          # Simulate deployment process
          sleep 2
          echo "Deployment completed successfully."
          echo "url=https://google.com/" >> $GITHUB_OUTPUT